# THIS FILE SETS UP CONFIG FOR VISUALIZATION OF THE SIMULATION

# Open Visualization
/vis/open OGLI

# Initial Viewpoint
/vis/viewer/set/viewpointVector 1 0 0

# Setup
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 10 cm
#/vis/scene/add/axes
/vis/scene/add/eventID

# Show maximum of 1000 events
/vis/scene/endOfEventAction accumulate 1000

# Run 1000 events (with verbosity)
/run/verbose 2
/run/beamOn 1000
